-- Tabla para controlar envío de recordatorios "agendar de nuevo" a 15, 30 y 60 días desde la última cita realizada.
-- Ejecutar UNA sola vez en Railway → Query. Pega y ejecuta SOLO el siguiente bloque (una sola sentencia).

CREATE TABLE IF NOT EXISTS recordatorio_post_cita (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id INTEGER NOT NULL,
    cita_id INTEGER NOT NULL,
    enviado_dia_15_at DATE,
    enviado_dia_30_at DATE,
    enviado_dia_60_at DATE
);

-- Si ya creaste la tabla desde la UI de Railway, NO ejecutes lo de arriba. El error "recordatorio_post_cita_id_seq"
-- suele salir al usar SERIAL o al ejecutar varias sentencias juntas; con esta versión se evita.
